import browser from "webextension-polyfill";

import { createElement, getBrowser } from "../utils/dom";
import { Logger } from "../utils/logger";
import Modal from "../utils/modal";
import { BETA_TESTS, Setting, updateSettings } from "../utils/settings";
import { SchoologyTheme } from "../utils/theme-model";
import { createToastButton, showToast } from "../utils/toast";

export async function load() {
    await preload();

    alertAutoGeneratedTheme();
    handleBetaFeatures();
    updateDefaultDomainSetting();
    pageModifications();
}

async function preload() {
    Logger.log(
        `Loaded Schoology Plus version ${browser.runtime.getManifest().version}${
            getBrowser() != "Chrome" || (browser.runtime.getManifest() as any).update_url
                ? ""
                : " (development version)"
        }`
    );
    document.documentElement.setAttribute("page", location.pathname);

    await updateSettings();

    new Setting(
        "defaultDomain",
        "Default Schoology Domain",
        "The website on which Schoology Plus runs. Cannot be changed here.",
        "app.schoology.com",
        "text",
        {
            disabled: true,
        },
        value => value,
        undefined,
        element => element.value
    );

    Logger.debug("Finished loading preload.js");
}

function alertAutoGeneratedTheme() {
    // Inform user about theme
    if (localStorage["splus-temp-generatedtheme"]) {
        localStorage.removeItem("splus-temp-generatedtheme");

        showToast(
            "Theme Generated",
            "Schoology Plus created a theme that matches your school's theme",
            "rgb(0,255,0)",
            {
                buttons: [
                    createToastButton(
                        "View Themes",
                        "view-themes-button",
                        () => (location.href = browser.runtime.getURL("/theme-editor.html"))
                    ),
                ],
            }
        );
    }
}

function handleBetaFeatures() {
    let betaCode = Setting.getValue<string>("beta");
    let betaSection = null;
    if (betaCode && betaCode in BETA_TESTS) {
        // Beta Enabled Notice
        let betaTag = createElement("span", ["splus-beta-tag", "splus-track-clicks"], {
            textContent: "β",
            id: "beta-tag",
        });
        betaTag.addEventListener("click", event => Modal.openModal("beta-modal"));
        let betaContainer = createElement("div", ["splus-beta-container"], {}, [betaTag]);
        document.body.append(betaContainer);
        betaSection = createBetaSection(betaCode);
        betaContainer.append(betaSection);
    }

    function createBetaSection(name: string) {
        return createElement("div", ["splus-beta-section"], { id: `splus-beta-section-${name}` }, [
            createElement("h3", [], { textContent: name }),
        ]);
    }

    function createBetaToggleCheckbox(
        name: string,
        onchange: () => void,
        checked = false,
        nestingLevel = 1
    ) {
        return createElement(
            "div",
            ["splus-beta-toggle"],
            { style: { paddingLeft: `${(nestingLevel - 1) * 10}px` } },
            [
                createElement("label", [], { textContent: name }),
                createElement("input", [], {
                    type: "checkbox",
                    checked: checked,
                    onchange: onchange,
                }),
            ]
        );
    }
}

function updateDefaultDomainSetting() {
    // Check Schoology domain
    setTimeout(checkDomain, 2000);

    async function checkDomain() {
        const DISALLOWED_DOMAINS = [
            "asset-cdn.schoology.com",
            "developer.schoology.com",
            "support.schoology.com",
            "info.schoology.com",
            "files-cdn.schoology.com",
            "status.schoology.com",
            "ui.schoology.com",
            "www.schoology.com",
            "api.schoology.com",
            "developers.schoology.com",
            "schoology.com",
            "error-page.schoology.com",
            "app-msft-teams.schoology.com",
            "lti-submission-google.app.schoology.com",
            "lti-submission-microsoft.app.schoology.com",
            "googledrive.app.schoology.com",
            "onedrive.app.schoology.com",
        ];

        let dd = Setting.getValue<string>("defaultDomain");

        if (
            dd !== window.location.hostname &&
            !DISALLOWED_DOMAINS.includes(window.location.hostname) &&
            !window.location.hostname.match(/.*[-\.]app\.schoology\.com/)
        ) {
            await Setting.setValue("defaultDomain", window.location.hostname);

            let bgColor =
                document.querySelector<HTMLElement>("#header header")!.style.backgroundColor;

            if (
                bgColor &&
                !["app.schoology.com", "lms.lausd.net"].includes(window.location.hostname)
            ) {
                let t = {
                    name: `Auto Generated Theme for ${window.location.hostname}`,
                    version: 2,
                    color: {
                        custom: {
                            primary: bgColor,
                            hover: "rgb(2, 79, 125)",
                            background: "rgb(2, 79, 125)",
                            border: "rgb(2, 79, 125)",
                        },
                    },
                    logo: {
                        preset: "default",
                    },
                };

                localStorage["splus-temp-generatedtheme"] = true;

                let s = await browser.storage.sync.get({ themes: [] });
                let themes = (s as { themes: SchoologyTheme[] }).themes.filter(
                    x => x.name !== `Auto Generated Theme for ${window.location.hostname}`
                );
                themes.push(t as SchoologyTheme);
                await browser.storage.sync.set({ themes: themes });
                Logger.log(
                    `Schoology Plus has updated the domain on which it runs.\nPrevious: ${dd}\nNew: ${window.location.hostname}`
                );
                location.reload();
            } else {
                Logger.log(
                    `Schoology Plus has updated the domain on which it runs.\nPrevious: ${dd}\nNew: ${window.location.hostname}`
                );
                location.reload();
            }
        }
    }
}

function pageModifications() {
    // Page Modifications

    document.head.appendChild(
        createElement("meta", [], {
            name: "viewport",
            content: "width=device-width, initial-scale=1",
        })
    );
    let bottom = document.querySelector("span.Footer-copyright-2Vt6I");
    bottom?.appendChild(
        createElement("span", ["footer-divider"], { textContent: "|" }, [
            createElement("span", ["footer-text-enhanced-by"], {
                style: { cursor: "pointer" },
                onclick: () =>
                    window.open(
                        "https://schoologypl.us/?utm_source=ext-enhanced-by-footer",
                        "_blank"
                    ),
                textContent: "Enhanced by Schoology Plus",
            }),
        ])
    );

    document.documentElement.style.setProperty("--default-visibility", "visible");
}
